---
- name: Deploy Web App
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy Web Files
      copy:
        src: ../app/
        dest: /var/www/html/

